######################################################################
#
# File name : tb_D_FLIPFLOP_elaborate.do
# Created on: Sun Jan 21 00:27:20 UTC 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L simprims_ver -L secureip -work xil_defaultlib xil_defaultlib.tb_D_FLIPFLOP xil_defaultlib.glbl -o tb_D_FLIPFLOP_opt
