######################################################################
#
# File name : tb_D_FLIPFLOP_wave.do
# Created on: Sat Jan 20 22:30:56 UTC 2024
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
