set_property SRC_FILE_INFO {cfile:/home/azafeer/Desktop/test/small_des/small_des.srcs/constrs_1/new/io_planning.xdc rfile:../../../small_des.srcs/constrs_1/new/io_planning.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets clk_IBUF_BUFG]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF2 [get_cells q_reg]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X96Y237 [get_cells q_reg]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BUFCE [get_cells clk_IBUF_BUFG_inst]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCE_X0Y88 [get_cells clk_IBUF_BUFG_inst]
