######################################################################
#
# File name : tb_D_FLIPFLOP_wave.do
# Created on: Sat Jan 20 20:47:31 UTC 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
