######################################################################
#
# File name : tb_D_FLIPFLOP_elaborate.do
# Created on: Mon Jan 22 19:58:21 UTC 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
/cad/mentor/questasim_2019.4/questasim/bin/vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L secureip -work xil_defaultlib xil_defaultlib.tb_D_FLIPFLOP xil_defaultlib.glbl -o tb_D_FLIPFLOP_opt
