######################################################################
#
# File name : tb_D_FLIPFLOP_compile.do
# Created on: Sun Jan 21 00:28:51 UTC 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xil_defaultlib

vmap xil_defaultlib questa_lib/msim/xil_defaultlib

vlog -64 -incr -mfcu -work xil_defaultlib  \
"tb_D_FLIPFLOP_func_synth.v" \

vlog -64 -incr -mfcu -sv -work xil_defaultlib  \
"../../../../../small_des.srcs/sim_1/new/tb_D_FLIPFLOP.sv" \


