######################################################################
#
# File name : tb_D_FLIPFLOP_compile.do
# Created on: Mon Jan 22 19:41:03 UTC 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
/cad/mentor/questasim_2019.4/questasim/bin/vlib questa_lib/work
/cad/mentor/questasim_2019.4/questasim/bin/vlib questa_lib/msim

/cad/mentor/questasim_2019.4/questasim/bin/vlib questa_lib/msim/xil_defaultlib

/cad/mentor/questasim_2019.4/questasim/bin/vmap xil_defaultlib questa_lib/msim/xil_defaultlib

/cad/mentor/questasim_2019.4/questasim/bin/vlog -64 -incr -mfcu -sv -work xil_defaultlib "/home/azafeer/Desktop/test/small_des/small_des.gen/sources_1/bd/const_ip/hdl/const_ip_wrapper.v" \
"../../../../small_des.srcs/sources_1/new/D_FLIPFLOP.sv" \
"../../../../small_des.srcs/sim_1/new/tb_D_FLIPFLOP.sv" \


# compile glbl module
/cad/mentor/questasim_2019.4/questasim/bin/vlog -work xil_defaultlib "glbl.v"

