######################################################################
#
# File name : tb_D_FLIPFLOP_wave.do
# Created on: Sat Jan 20 21:21:42 UTC 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
