######################################################################
#
# File name : tb_D_FLIPFLOP_compile.do
# Created on: Sun Jan 21 13:48:58 UTC 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xil_defaultlib

vmap xil_defaultlib questa_lib/msim/xil_defaultlib

vlog -64 -incr -mfcu -sv -work xil_defaultlib  \
"../../../../small_des.srcs/sources_1/new/D_FLIPFLOP.sv" \
"../../../../small_des.srcs/sim_1/new/tb_D_FLIPFLOP.sv" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

